console.log(`.................. implicit conversion to string.................`);
result= '3'+ 2;
console.log(   ` Result is: ${result} , type of result is :${typeof result}`);
console.log(`why?: result is 32 it take 2 implicity string and perform concationtion on it`);
result= '3'+ true;
console.log( ` Result is: ${result},type of result is: ${typeof result}`);
console.log(`why?: result is 3true it take 3 implicity string and perform concationtion on it`);
result= '3'+ undefined;
console.log( `  Result is: ${result} ,type of result is: ${typeof result}`);
console.log(`why?: result is 3undefined take 3 implicity string and perform concationtion on it`);
result= '3'+ null;
console.log( `  Result is: ${result} ,type of result is: ${typeof result}`);
console.log(`why?: result is 3null it take 3 implicity string and perform concationtion on it`);
console.log(`......................................`);
result ='4'-true;
console.log( `  Result is: ${result} ,type of result is :${typeof result}`);
console.log(`why?: result is 3etake 4implicity string and perform concationtion on it`);
result ='4'+true;
console.log( `  Result is: ${result} ,type of result is: ${typeof result}`);
console.log(`why?: result is 4true take 4 implicity string and perform concationtion on it`);
result ='4'+false;
console.log( `  Result is: ${result} ,type of result is :${typeof result}`);

console.log(`................................`);
result='3'+ 2;
console.log(`   Result is: ${result} ,type of result is: ${typeof result}`);
console.log(`why?: result is 32 take 3 implicity string and perform concationtion on it`);
result='3'+ true;
console.log( `  Result is: ${result} ,type of result is: ${typeof result}`);
console.log(`why?: result is 3true take 3 implicity string and perform concationtion on it`);
result='3'+ undefined;
console.log( `  Result is: ${result} ,type of result is: ${typeof result}`);
console.log(`why?: result is 3undefined take 3 implicity string and perform concationtion on it`);
result='3'+ null;
console.log( `  Result is: ${result} ,type of result is: ${typeof result}`);
console.log(`why?: result is 3null take 3 implicity string and perform concationtion on it`);